openapi: "3.0.3"
info:
  title: API with Auth
  version: "1.0"
tags:
  - name: Order
    description: Operations related to order


paths:
  /orders:
    summary: Operation on orders
    get:
      parameters:
        - $ref: "#/components/parameters/PageParam"
        - $ref: "#/components/parameters/SizeParam"
      tags:
        - Order
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
    post:
      tags:
        - Order
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/Order"
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Order"


components:
  parameters:
    PageParam:
      name: page
      in: query
      required: false
      schema:
        type: integer
        example: 2
    SizeParam:
      name: size
      in: query
      required: false
      schema:
        type: integer
        example: 1
  schemas:
    Order:
      type: object
      description: An Order Schema
      properties:
        id:
          type: integer
          example: 1
        customer_name:
          type: string
          example: Rakoto
        creation_datetime:
          type: string
          format: date-time
          example: "2025-08-25T17:11:00Z"
        total_amount:
          type: integer
          format: float
          example: 10000.0
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      
      